2020-01-11 14:13:12,590 ERROR: Exception on /createdata [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 88, in createData
    return render_template('createdata.html', title='Create datasets', form=form)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/createdata.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/createdata.html", line 13, in block "content"
    {{ wtf.quick_form(form) }}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 205, in template
    {{ form_field(field,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 123, in template
    {{field(class="form-control", **kwargs)|safe}}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms/widgets/core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms_sqlalchemy/fields.py", line 107, in iter_choices
    for pk, obj in self._get_object_list():
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms_sqlalchemy/fields.py", line 100, in _get_object_list
    self._object_list = list((text_type(get_pk(obj)), obj) for obj in query)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms_sqlalchemy/fields.py", line 100, in <genexpr>
    self._object_list = list((text_type(get_pk(obj)), obj) for obj in query)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/wtforms_sqlalchemy/fields.py", line 189, in get_pk_from_identity
    cls, key = identity_key(instance=obj)
ValueError: too many values to unpack (expected 2)
2020-01-11 14:14:06,033 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 12:56:47,622 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 12:59:46,110 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:00:19,778 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:09:03,809 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:11:42,937 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:12:13,173 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:12:44,108 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:13:56,004 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:15:19,909 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:17:48,149 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:20:24,360 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:21:15,519 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:21:37,511 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:22:18,081 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:22:50,097 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:25:05,270 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-12 13:25:40,277 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
